[build.environment]
  NETLIFY_USE_YARN = "true"
  YARN_VERSION = "1.22.17"

[build]
   command = "npm run build:hugo"
  publish = "dist"

[context.deploy-preview]
  command = "yarn build:preview"

[dev]
  framework = "hugo"
  targetPort = 3000

